import { CartItems } from "./estore";

export interface YocoInputDto extends GeneralDto{
    publicKey: string;
    description: string
    [key: string]: any
}

export declare interface GeneralDto {
    amountInCents: number
    metadata: YocoPayMetadataDto
    customer: YocoPayCustomerDto
}
export declare interface YocoPayCustomerDto {
    email: string
    phone: string
    firstName: string
    lastName: string
}

/**
 * @description Metadata for the payment it has almost all data types for the
 *  e-store ranging from shiping address, customer details, etc. Most importantly the payment details generated by OCO frontend SDK are embeded in there under ,
 * @export interface YocoPayMetadataDto
 * @extends {YocoPayCustomerDto > PaymentDetailsDto > PaymentDetailsDto, GeneralDto}
 */
export declare interface EstoreCustomerDto extends PaymentDetailsDto {
    shippingAddress: string
    cartItems: CartItems[]
}

export declare interface YocoPayMetadataDto extends YocoPayCustomerDto{
    affliate: string
}

export interface PaymentDetailsDto extends GeneralDto {
    currency: string
    token: string
}

export interface PaymentResponse {
    success: boolean
    message: string
    [key: string]: any
}